 server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
 spring:
  jackson:
    default-property-inclusion: NON_NULL
  thymeleaf:
    #resources.static-locations=classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true&serverTimezone=UTC 
    url: jdbc:mysql://192.168.2.200:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true&serverTimezone=UTC 
    username: root
#    password: 123456
    password: WANGtao005@hotmail.com
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎,该引不是事务安全的，而且不支持外键
    show-sql: true
    hibernate:
      ddl-auto: update
  activiti:
    # 自动建表
    database-schema: activiti
    database-schema-update: true
    history-level: full
    db-history-used: true
#  # 关闭activiti登录验证  ,这里因为用的spring boot 2.1.4 所以该配置是无法生效的,默认登录用户名 user,密码是启动时生成在控制台的密码
#  security:
#    basic:
#      enabled: false



 